version: "3.9"

services:
  cpp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp_dev_env
    volumes:
      - ./src:/app/src # Mount your local source folder
    working_dir: /app
    tty: true # Keeps the container open (interactive)
